name: deploy ecs

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'ECR image tag to deploy (optional)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_REPOSITORY: "ecspresso-demo-nginx"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.inputs.image_tag == ''
    outputs:
      ECR_IMAGE_TAG: ${{ steps.set-ecr-image-tag.outputs.ECR_IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v4

      # ref: https://zenn.dev/kou_pg_0131/articles/gh-actions-ecr-push-image
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::083636136646:role/gha-deploy-ecs-role"

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR Image Tag
        id: set-ecr-image-tag
        run: |
          echo "ECR_IMAGE_TAG=$(date +%Y%m%d%H%M%S)-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: build and push docker image to ecr
        env:
          ECR_IMAGE_TAG: ${{ steps.set-ecr-image-tag.outputs.ECR_IMAGE_TAG }}
        run: |
          docker build . --tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.ECR_IMAGE_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::083636136646:role/gha-deploy-ecs-role"

      - name: "install ecspresso"
        uses: kayac/ecspresso@v2
        with:
          version: v2.4.1

      - name: "Set ECR Image Tag"
        run: |
          if [ -n "${{ github.event.inputs.image_tag }}" ]; then
            echo "ECR_IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "ECR_IMAGE_TAG=${{ needs.build.outputs.ECR_IMAGE_TAG }}" >> $GITHUB_ENV
          fi

      - name: "deploy ecs"
        run: ecspresso deploy --config ecspresso-config.yaml
        working-directory: ./
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          ECR_IMAGE_TAG: ${{ env.ECR_IMAGE_TAG }}
          AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
